AmbientRouteValuesDotNetCore3.1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AmbientRouteValuesDotNetCore3_1.Controllers
{
    public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

AmbientRouteValuesDotNetCore3.1/Controllers/TestAController.cs
using Microsoft.AspNetCore.Mvc;

namespace AmbientRouteValuesDotNetCore3_1.Controllers
{
    public class TestAController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

AmbientRouteValuesDotNetCore3.1/Controllers/TestBController.cs
using Microsoft.AspNetCore.Mvc;

namespace AmbientRouteValuesDotNetCore3_1.Controllers
{
    public class TestBController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

AmbientRouteValuesDotNetCore3.1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

AmbientRouteValuesDotNetCore3.1/Views/Shared/_Layout.cshtml
<html>
<head></head>
<body>
    <h1>.NET Core 3.1</h1>
    <h2>@ViewBag.Title</h2>
    
    <a href="@Url.Action("Index", "Home", new { culture = ""})">Default culture</a>
    <a href="@Url.Action("Index", "Home", new { culture = "ru"})">Russian culture</a>
    
    <h3>Instructions</h3>
    <ol>
        <li>Go to russian culture <code>/ru</code></li>
        <li>Review destination URLs for each link below</li>
    </ol>

    <ul>
        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
        <li><a href="@Url.Action("Index", "TestA")">TestA</a></li>
        <li><a href="@Url.Action("Index", "TestB")">TestB</a></li>
    </ul>

    @RenderBody()
</body>
</html>

AmbientRouteValuesDotNetCore3.1/Views/TestA/Index.cshtml
@{
    ViewBag.Title = "TestA";
}

AmbientRouteValuesDotNetCore3.1/Views/TestB/Index.cshtml
@{
    ViewBag.Title = "TestB";
}